project:
  type: website
  output-dir: docs
website:
  title: "Verso"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ryan-heslin
      - text: LinkedIn
        href: https://www.linkedin.com/in/ryan-heslin/
  search:
    collapse-after: 3
    copy-button: true
format:
  html:
    theme: journal
    css: "styles.css"
execute: 
  freeze: auto
